yelp_api_key = 'gb_wrkilRgmDegSZJcEufnWcS4R3tgMTbVc0DhWM72rGUokjmLyY-XAl1OpxDHor-UWrFdzyGWbmnMTB_Tu8e3REmVLj8YwABWczjUeat_m59j_dEOajGYRP0wuYXHYx'

google_api_key = 'AIzaSyD2X0p2LPK0TMZJyLm7uzzt45uhbBlXEE4'